# This is a basic workflow to help you get started with Actions

name: push readme

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Push the readme to user profile
        uses: apgapg/copy_file_to_another_repo_action@dev/rename-destination-file
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'README.md'
          rename: 'trtle.md'
          destination_repo: 'Saltyparts/Saltyparts.github.io'
          destination_folder: 'src'
          user_email: 'chaynabors@gmail.com'
          user_name: 'Saltyparts'
          commit_message: 'update trtle readme'

